version: '3'
services:
    server:
      build:
        context: ./server
        dockerfile: ./Dockerfile
      image: dc_server
      ports:
        - "8000:8000"
    client:
      build:
        context: ./client
        dockerfile: ./Dockerfile
      image: dc_client
      depends_on:
        - server


